// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irrevufojshrrhrduczt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlycmV2dWZvanNocnJocmR1Y3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjUzMTQsImV4cCI6MjA2NDM0MTMxNH0.kldhxo4dICOftI2WKiKqGoiuEvXsBYX_ulhJry7LJMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);